<?php
	/* Generated by Wixnit Class Builder 
	// Apr, 05/2020
	// Building get routine for class Property
	*/


	session_start();
	//---------- Include files

	//require_once("../db.php");

	//---------- End of include


	$property = new Property($_REQUEST['Propertyid']);

	$ret = new stdClass();
	$ret->Status = "ACCESS_DENIED";
	$ret->Data = "";
	$ret->Message = "Please login again";

	//If user verification is used
	//if(isset($_SESSION['']) === true)
	//{
		$ret->Status = "SUCCESS";

		$r = new stdClass();
		$r->Property = $property;

		//Optional data getting
		/*
		$r->Owner = Property->Owner;
		*/
		$ret->Data = $r;
		$ret->Message= "DONE";
	//}
	echo json_encode($ret);
	
