<?php
	/* Generated by Wixnit Class Builder 
	// Apr, 06/2020
	// Building get routine for class Partner
	*/


	session_start();
	//---------- Include files

	//require_once("../db.php");

	//---------- End of include


	$partner = new Partner($_REQUEST['Partnerid']);

	$ret = new stdClass();
	$ret->Status = "ACCESS_DENIED";
	$ret->Data = "";
	$ret->Message = "Please login again";

	//If user verification is used
	//if(isset($_SESSION['']) === true)
	//{
		$ret->Status = "SUCCESS";
		$ret->Data = $partner;
		$ret->Message= "DONE";
	//}
	echo json_encode($ret);
	
