<?php
	/* Generated by Wixnit Class Builder 
	// Apr, 06/2020
	// Building get routine for class Vehicle
	*/


	session_start();
	//---------- Include files

	//require_once("../db.php");

	//---------- End of include


	$vehicle = new Vehicle($_REQUEST['Vehicleid']);

	$ret = new stdClass();
	$ret->Status = "ACCESS_DENIED";
	$ret->Data = "";
	$ret->Message = "Please login again";

	//If user verification is used
	//if(isset($_SESSION['']) === true)
	//{
		$ret->Status = "SUCCESS";

		$r = new stdClass();
		$r->Vehicle = $vehicle;

		//Optional data getting
		/*
		$r->Driver = Vehicle->Driver;
		$r->Owner = Vehicle->Owner;
		*/
		$ret->Data = $r;
		$ret->Message= "DONE";
	//}
	echo json_encode($ret);
	
