<?php
	/* Generated by Wixnit Class Builder 
	// May, 16/2020
	// Building class for Fundingrequest
	*/

	class Fundingrequest
	{
		public $Id = "";
		public $Created = 0;
		public $Customer = "";
		public $Amount = 0;
		public $Method = "";
		public $Accountname = "";
		public $Slipnumber = "";
		public $Confirmed = false;
		public $Declined = false;
		public $Status = false;
		public $Confirmdate = 0;

		function __construct($arg=null)
		{
			if($arg != null)
			{
				$db = DB::GetDB();

				$res = $db->query("SELECT * FROM fundingrequest WHERE fundingrequestid='$arg'");

				if($res->num_rows > 0)
				{
					$row = $res->fetch_assoc();
				
					$this->Id = $row['fundingrequestid'];
					$this->Created = new WixDate($row['created']);
					$this->Customer = new Customer($GLOBALS['subscriber']);
					$this->Customer->Initialize($row['customer']);
					$this->Amount = $row['amount'];
					$this->Method = $row['method'];
					$this->Accountname = $row['accountname'];
					$this->Slipnumber = $row['slipnumber'];
					$this->Confirmed = Convert::ToBool($row['confirmed']);
					$this->Declined = Convert::ToBool($row['declined']);
					$this->Status = Convert::ToBool($row['status']);
					$this->Confirmdate = new WixDate($row['confirmdate']);
				}
			}
		}

		public function Save()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$created = time();
			$customer = addslashes(is_a($this->Customer, "Customer") ? $this->Customer->Id : $this->Customer);
			$amount = floatval($this->Amount);
			$method = addslashes($this->Method);
			$accountname = addslashes($this->Accountname);
			$slipnumber = addslashes($this->Slipnumber);
			$confirmed = Convert::ToInt($this->Confirmed);
			$declined = Convert::ToInt($this->Declined);
			$status = Convert::ToInt($this->Status);
			$confirmdate = Convert::ToInt(is_a($this->Confirmdate, "WixDate") ? $this->Confirmdate->Id : $this->Confirmdate);

			if($res = $db->query("SELECT fundingrequestid FROM fundingrequest WHERE fundingrequestid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE fundingrequest SET customer='$customer',amount='$amount',method='$method',accountname='$accountname',slipnumber='$slipnumber',confirmed='$confirmed',declined='$declined',status='$status',confirmdate='$confirmdate' WHERE fundingrequestid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT fundingrequestid FROM fundingrequest WHERE fundingrequestid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO fundingrequest(fundingrequestid,created,customer,amount,method,accountname,slipnumber,confirmed,declined,status,confirmdate) VALUES ('$id','$created','$customer','$amount','$method','$accountname','$slipnumber','$confirmed','$declined','$status','$confirmdate')");
			}
		}

		public function Delete()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM fundingrequest WHERE fundingrequestid='$id'");

			//Deleting Associated Objects
			/*n			$this->Customer->Delete();

			$this->Confirmdate->Delete();
			*/
		}

		public static function Search($term='')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM fundingrequest WHERE customer LIKE '%$term%' OR amount LIKE '%$term%' OR method LIKE '%$term%' OR accountname LIKE '%$term%' OR slipnumber LIKE '%$term%' OR confirmed LIKE '%$term%' OR declined LIKE '%$term%' OR status LIKE '%$term%' OR confirmdate LIKE '%$term%'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Fundingrequest();
                $ret[$i]->Id = $row['fundingrequestid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Customer = $row['customer'];
                $ret[$i]->Amount = $row['amount'];
                $ret[$i]->Method = $row['method'];
                $ret[$i]->Accountname = $row['accountname'];
                $ret[$i]->Slipnumber = $row['slipnumber'];
                $ret[$i]->Confirmed = Convert::ToBool($row['confirmed']);
                $ret[$i]->Declined = Convert::ToBool($row['declined']);
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $ret[$i]->Confirmdate = new WixDate($row['confirmdate']);
				$i++;
			}
			return Fundingrequest::GroupInitialize($ret);
		}

		public static function Filter($term='', $field='fundingrequestid')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM fundingrequest WHERE ".$field." ='$term'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Fundingrequest();
                $ret[$i]->Id = $row['fundingrequestid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Customer = $row['customer'];
                $ret[$i]->Amount = $row['amount'];
                $ret[$i]->Method = $row['method'];
                $ret[$i]->Accountname = $row['accountname'];
                $ret[$i]->Slipnumber = $row['slipnumber'];
                $ret[$i]->Confirmed = Convert::ToBool($row['confirmed']);
                $ret[$i]->Declined = Convert::ToBool($row['declined']);
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $ret[$i]->Confirmdate = new WixDate($row['confirmdate']);
				$i++;
			}
			return $ret;
		}

		public static function Order($field='id', $order='DESC')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM fundingrequest ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Fundingrequest();
                $ret[$i]->Id = $row['fundingrequestid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Customer = $row['customer'];
                $ret[$i]->Amount = $row['amount'];
                $ret[$i]->Method = $row['method'];
                $ret[$i]->Accountname = $row['accountname'];
                $ret[$i]->Slipnumber = $row['slipnumber'];
                $ret[$i]->Confirmed = Convert::ToBool($row['confirmed']);
                $ret[$i]->Declined = Convert::ToBool($row['declined']);
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $ret[$i]->Confirmdate = new WixDate($row['confirmdate']);
				$i++;
			}
			return $ret;
		}

		public static function All()
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM fundingrequest");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Fundingrequest();
				$ret[$i]->Id = $row['fundingrequestid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Customer = $row['customer'];
				$ret[$i]->Amount = $row['amount'];
				$ret[$i]->Method = $row['method'];
				$ret[$i]->Accountname = $row['accountname'];
				$ret[$i]->Slipnumber = $row['slipnumber'];
				$ret[$i]->Confirmed = Convert::ToBool($row['confirmed']);
				$ret[$i]->Declined = Convert::ToBool($row['declined']);
				$ret[$i]->Status = Convert::ToBool($row['status']);
				$ret[$i]->Confirmdate = new WixDate($row['confirmdate']);
				$i++;
			}
			return $ret;
		}

		public function ByUser($customer)
        {
            $db = DB::GetDB();
            $ret = array();
            $i = 0;

            $id = is_a($customer, "Customer") ? $customer->Id : $customer;

            $res = $db->query("SELECT * FROM fundingrequest WHERE customer='$id' ORDER BY id DESC");
            while(($row = $res->fetch_assoc()) != null)
            {
                $ret[$i] = new Fundingrequest();
                $ret[$i]->Id = $row['fundingrequestid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Customer = $row['customer'];
                $ret[$i]->Amount = $row['amount'];
                $ret[$i]->Method = $row['method'];
                $ret[$i]->Accountname = $row['accountname'];
                $ret[$i]->Slipnumber = $row['slipnumber'];
                $ret[$i]->Confirmed = Convert::ToBool($row['confirmed']);
                $ret[$i]->Declined = Convert::ToBool($row['declined']);
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $ret[$i]->Confirmdate = new WixDate($row['confirmdate']);
                $i++;
            }
            return $ret;
        }
	}
