<?php
	/* Generated by Wixnit Class Builder 
	// Jan, 10/2020
	// Building class for Message
	*/

	class Message
	{
		public $Id = "";
		public $Created = 0;
		public $Name = "";
		public $Surname = "";
		public $Phone = "";
		public $Email = "";
		public $Status = false;
		public $Stared = false;
		public $Subject = "";
		public $Body = "";
		public $Seen = false;
		public $Opened = false;
		public $Property = null;
		public $Sender = "";

		public $Type = "message";

		private $subscriber = null;

		function __construct($subscriber = null)
		{
            $this->subscriber = $subscriber;
		}

		public function Initialize($arg=null)
        {
            if($arg != null)
            {
                $db = DB::GetDB();

                $res = $db->query("SELECT * FROM message WHERE messageid='$arg'");

                if($res->num_rows > 0)
                {
                    $row = $res->fetch_assoc();

                    $this->Id = $row['messageid'];
                    $this->Created = new WixDate($row['created']);
                    $this->Name = $row['name'];
                    $this->Surname = $row['surname'];
                    $this->Phone = $row['phone'];
                    $this->Email = $row['email'];
                    $this->Status = Convert::ToBool($row['status']);
                    $this->Stared = Convert::ToBool($row['stared']);
                    $this->Subject = $row['subject'];
                    $this->Body = $row['body'];
                    $this->Seen = Convert::ToBool($row['seen']);
                    $this->Opened = Convert::ToBool($row['opened']);
                    $this->Property = new Property($row['property']);
                    $this->Sender = $row['sender'];
                }
            }
        }

		public function Save()
		{
            $db = DB::GetDB();

			$id = $this->Id;
			$created = time();
			$name = addslashes($this->Name);
			$surname = addslashes($this->Surname);
			$phone = addslashes($this->Phone);
			$email = addslashes($this->Email);
			$status = Convert::ToInt(addslashes($this->Status));
			$stared = Convert::ToInt($this->Stared);
			$subject = addslashes($this->Subject);
			$body = addslashes($this->Body);
			$seen = Convert::ToInt($this->Seen);
			$opened = Convert::ToInt($this->Opened);

			$sender = addslashes($this->Sender);
			$property = addslashes(is_a($this->Property, "Property") ? $this->Property->Id : $this->Property);

			if($res = $db->query("SELECT messageid FROM message WHERE messageid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE message SET name='$name',surname='$surname',phone='$phone',email='$email',status='$status',stared='$stared',subject='$subject',body='$body',seen='$seen',opened='$opened',property='$property',sender='$property' WHERE messageid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT messageid FROM message WHERE messageid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO message(messageid,created,name,surname,phone,email,status,stared,subject,body,seen,opened,sender,property) VALUES ('$id','$created','$name','$surname','$phone','$email','$status','$stared','$subject','$body','$seen','$opened','$sender','$property')");
			}
		}

		public function Delete()
		{
            $db = DB::GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM message WHERE messageid='$id'");
		}

		public static function Search($property, $term='')
		{
            $db = DB::GetDB();
			$ret = array();
			$i = 0;

			$id = $_REQUEST['property'];

			$res = $db->query("SELECT * FROM `message` WHERE property='$id' AND (`name` LIKE '%$term%' OR surname LIKE '%$term%' OR phone LIKE '%$term%' OR email LIKE '%$term%' OR `status` LIKE '%$term%' OR stared LIKE '%$term%' OR `subject` LIKE '%$term%' OR body LIKE '%$term%') ORDER BY id DESC");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Message();
                $ret[$i]->Id = $row['messageid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Name = $row['name'];
                $ret[$i]->Surname = $row['surname'];
                $ret[$i]->Phone = $row['phone'];
                $ret[$i]->Email = $row['email'];
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $ret[$i]->Stared = Convert::ToBool($row['stared']);
                $ret[$i]->Subject = $row['subject'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Seen = Convert::ToBool($row['seen']);
                $ret[$i]->Opened = Convert::ToBool($row['opened']);
                $ret[$i]->Sender = $row['sender'];
                $ret[$i]->Property = new Property($row['property']);
				$i++;
			}
			return $ret;
		}

		public static function Filter($property, $term='', $field='messageid')
		{
            $db = DB::GetDB();
			$ret = array();
			$i = 0;

			$id = is_a($property, "Property") ? $property->Id : $property;

			$res = $db->query("SELECT * FROM message WHERE property='$id' AND ".$field." ='$term' ORDER BY id DESC");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Message();
                $ret[$i]->Id = $row['messageid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Name = $row['name'];
                $ret[$i]->Surname = $row['surname'];
                $ret[$i]->Phone = $row['phone'];
                $ret[$i]->Email = $row['email'];
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $ret[$i]->Stared = Convert::ToBool($row['stared']);
                $ret[$i]->Subject = $row['subject'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Seen = Convert::ToBool($row['seen']);
                $ret[$i]->Opened = Convert::ToBool($row['opened']);
                $ret[$i]->Sender = $row['sender'];
                $ret[$i]->Property = new Property($row['property']);
				$i++;
			}
			return $ret;
		}

		public static function Order(Subscriber $subscriber, $field='id', $order='DESC')
		{
            $db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM message ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Message($subscriber);
                $ret[$i]->Id = $row['messageid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Name = $row['name'];
                $ret[$i]->Surname = $row['surname'];
                $ret[$i]->Phone = $row['phone'];
                $ret[$i]->Email = $row['email'];
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $ret[$i]->Stared = Convert::ToBool($row['stared']);
                $ret[$i]->Subject = $row['subject'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Seen = Convert::ToBool($row['seen']);
                $ret[$i]->Opened = Convert::ToBool($row['opened']);
                $ret[$i]->Sender = $row['sender'];
                $ret[$i]->Property = new Property($row['property']);
				$i++;
			}
			return $ret;
		}

		public static function All($property)
		{
            $db = DB::GetDB();
			$ret = array();
			$i = 0;

			$id = is_a($property, "Property") ? $property->Id : $property;

			$res = $db->query("SELECT * FROM message WHERE property='$id' ORDER BY id DESC");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Message();
				$ret[$i]->Id = $row['messageid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Name = $row['name'];
				$ret[$i]->Surname = $row['surname'];
				$ret[$i]->Phone = $row['phone'];
				$ret[$i]->Email = $row['email'];
                $ret[$i]->Status = Convert::ToBool($row['status']);
				$ret[$i]->Stared = Convert::ToBool($row['stared']);
				$ret[$i]->Subject = $row['subject'];
				$ret[$i]->Body = $row['body'];
                $ret[$i]->Seen = Convert::ToBool($row['seen']);
                $ret[$i]->Opened = Convert::ToBool($row['opened']);
                $ret[$i]->Sender = $row['sender'];
                $ret[$i]->Property = new Property($row['property']);
				$i++;
			}
			return $ret;
		}


        public static function Stared($property, $term)
        {
            $db = DB::GetDB();
            $ret = array();
            $i = 0;

            $id = is_a($property, "Property") ? $property->Id : $property;

            $res = $db->query("SELECT * FROM message WHERE property='$id' AND (stared=1 AND (name LIKE '%$term%' OR surname LIKE '%$term%' OR phone LIKE '%$term%' OR email LIKE '%$term%' OR  subject LIKE '%$term%' OR body LIKE '%$term%')) ORDER BY id DESC");
            while(($row = $res->fetch_assoc()) != null)
            {
                $ret[$i] = new Message();
                $ret[$i]->Id = $row['messageid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Name = $row['name'];
                $ret[$i]->Surname = $row['surname'];
                $ret[$i]->Phone = $row['phone'];
                $ret[$i]->Email = $row['email'];
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $ret[$i]->Stared = Convert::ToBool($row['stared']);
                $ret[$i]->Subject = $row['subject'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Seen = Convert::ToBool($row['seen']);
                $ret[$i]->Opened = Convert::ToBool($row['opened']);
                $ret[$i]->Sender = $row['sender'];
                $ret[$i]->Property = new Property($row['property']);
                $i++;
            }
            return $ret;
        }


        public static function Resolved($property, $term)
        {
            $db = DB::GetDB();
            $ret = array();
            $i = 0;

            $id = is_a($property, "Property") ? $property->Id : $property;

            $res = $db->query("SELECT * FROM message WHERE property='$id' AND (status=1 AND (name LIKE '%$term%' OR surname LIKE '%$term%' OR phone LIKE '%$term%' OR email LIKE '%$term%' OR  subject LIKE '%$term%' OR body LIKE '%$term%')) ORDER BY id DESC");
            while(($row = $res->fetch_assoc()) != null)
            {
                $ret[$i] = new Message();
                $ret[$i]->Id = $row['messageid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Name = $row['name'];
                $ret[$i]->Surname = $row['surname'];
                $ret[$i]->Phone = $row['phone'];
                $ret[$i]->Email = $row['email'];
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $ret[$i]->Stared = Convert::ToBool($row['stared']);
                $ret[$i]->Subject = $row['subject'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Seen = Convert::ToBool($row['seen']);
                $ret[$i]->Opened = Convert::ToBool($row['opened']);
                $ret[$i]->Sender = $row['sender'];
                $ret[$i]->Property = new Property($row['property']);
                $i++;
            }
            return $ret;
        }


        public static function Unresolved($property, $term)
        {
            $db = DB::GetDB();
            $ret = array();
            $i = 0;

            $id = is_a($property, "Property") ? $property->Id : $property;

            $res = $db->query("SELECT * FROM message WHERE property='$id' AND (status=0 AND (name LIKE '%$term%' OR surname LIKE '%$term%' OR phone LIKE '%$term%' OR email LIKE '%$term%' OR  subject LIKE '%$term%' OR body LIKE '%$term%')) ORDER BY id DESC");
            while(($row = $res->fetch_assoc()) != null)
            {
                $ret[$i] = new Message();
                $ret[$i]->Id = $row['messageid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Name = $row['name'];
                $ret[$i]->Surname = $row['surname'];
                $ret[$i]->Phone = $row['phone'];
                $ret[$i]->Email = $row['email'];
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $ret[$i]->Stared = Convert::ToBool($row['stared']);
                $ret[$i]->Subject = $row['subject'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Seen = Convert::ToBool($row['seen']);
                $ret[$i]->Opened = Convert::ToBool($row['opened']);
                $ret[$i]->Sender = $row['sender'];
                $ret[$i]->Property = new Property($row['property']);
                $i++;
            }
            return $ret;
        }

        public static function ByProperty($property)
        {
            $db = DB::GetDB();
            $ret = array();
            $i = 0;

            $id = is_a($property, "Property") ? $property->Id : $property;

            $res = $db->query("SELECT * FROM message WHERE property='$id'");
            while(($row = $res->fetch_assoc()) != null)
            {
                $ret[$i] = new Message();
                $ret[$i]->Id = $row['messageid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Name = $row['name'];
                $ret[$i]->Surname = $row['surname'];
                $ret[$i]->Phone = $row['phone'];
                $ret[$i]->Email = $row['email'];
                $ret[$i]->Status = Convert::ToBool($row['status']);
                $ret[$i]->Stared = Convert::ToBool($row['stared']);
                $ret[$i]->Subject = $row['subject'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Seen = Convert::ToBool($row['seen']);
                $ret[$i]->Opened = Convert::ToBool($row['opened']);
                $ret[$i]->Sender = $row['sender'];
                $ret[$i]->Property = new Property($row['property']);
                $i++;
            }
            return $ret;
        }

		public function markSeen()
        {
            $db = DB::GetDB();
            $id = $this->Id;
            $db->query("UPDATE message SET seen=1 WHERE messageid='$id'");
            $db->close();
        }

        public function markOpened()
        {
            $db = DB::GetDB();
            $id = $this->Id;
            $db->query("UPDATE message SET opened=1 WHERE messageid='$id'");
            $db->close();
        }

        public static function markListSeen($property, $list)
        {
            $db = DB::GetDB();

            $id = is_a($property, "Property") ? $property->Id : $property;

            if(is_array($list))
            {
                if(count($list) > 0)
                {
                    $query = "UPDATE message SET seen=1 WHERE WHERE property='$id' AND messageid='".$list[0]->Id."'";

                    for($i = 1; $i < count($list); $i++)
                    {
                        $query .= " || messageid='".$list[$i]->Id."'";
                    }

                    $db->query($query);
                    $db->close();
                }
            }
        }

        public static function Staredcount($property)
        {
            $ret = 0;
            $db = DB::GetDB();
            $id = is_a($property, "Property") ? $property->Id : $property;

            $ret = $db->query("SELECT id FROM message WHERE property='$id' AND stared=1")->num_rows;
            $db->close();
            return $ret;
        }

        public static function Resolvedcount($property)
        {
            $ret = 0;
            $db = DB::GetDB();
            $id = is_a($property, "Property") ? $property->Id : $property;

            $ret = $db->query("SELECT id FROM message WHERE property='$id' AND status=1")->num_rows;
            $db->close();
            return $ret;
        }

        public static function Unresolvedcount($property)
        {
            $ret = 0;
            $db = DB::GetDB();
            $id = is_a($property, "Property") ? $property->Id : $property;

            $ret = $db->query("SELECT id FROM message WHERE property='$id' AND status=0")->num_rows;
            $db->close();
            return $ret;
        }

        public static function Totalcount($property)
        {
            $ret = 0;
            $db = DB::GetDB();
            $id = is_a($property, "Property") ? $property->Id : $property;

            $ret = $db->query("SELECT id FROM message WHERE property='$id'")->num_rows;
            $db->close();
            return $ret;
        }

        public static function Newcount($property)
        {
            $ret = 0;
            $db = DB::GetDB();
            $id = is_a($property, "Property") ? $property->Id : $property;

            $ret = $db->query("SELECT id FROM message WHERE property='$id' AND seen=0")->num_rows;
            $db->close();
            return $ret;
        }

        public static function Unreadcount($property)
        {
            $ret = 0;
            $db = DB::GetDB();
            $id = is_a($property, "Property") ? $property->Id : $property;

            $ret = $db->query("SELECT id FROM message WHERE property='$id' AND opened=0")->num_rows;
            $db->close();
            return $ret;
        }
	}
