<?php
	/* Generated by Wixnit Class Builder 
	// Sep, 01/2019
	// Building class for Faq
	*/

	class Partnerfaq
	{
		public $Id = "";
		public $Created = 0;
		public $Question = "";
		public $Answer = "";
		public $Category = "";
		public $Sort = 0;
		public $Status = false;
		
		private $subscriber = null;

		function __construct(Subscriber $subscriber)
		{
			$this->subscriber = $subscriber;
		}
		
		function Initialize($arg=null)
		{
			if($arg != null)
			{
				$db = $this->subscriber->GetDB();

				$res = $db->query("SELECT * FROM partnerfaq WHERE partnerfaqid='$arg'");

				if($res->num_rows > 0)
				{
					$row = $res->fetch_assoc();
				
					$this->Id = $row['partnerfaqid'];
					$this->Created = new WixDate($row['created']);
					$this->Question = $row['question'];
					$this->Answer = $row['answer'];
					$this->Category = new faqcategory($this->subscriber);
					$this->Category->Initialize($row['category']);
					$this->Sort = $row['sort'];
					$this->Status = Convert::ToBool($row['status']);
				}
			}
		}

		public function Save()
		{
			$db = $this->subscriber->GetDB();

			$id = $this->Id;
			$created = time();
			$question = addslashes($this->Question);
			$answer = addslashes($this->Answer);
			$category = addslashes(is_a($this->Category, "partnerfaqcategory") ? $this->Category->Id : $this->Category);
			$sort = Convert::ToInt($this->Sort);
			$status = Convert::ToInt($this->Status);

			if($res = $db->query("SELECT partnerfaqid FROM partnerfaq WHERE partnerfaqid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE partnerfaq SET question='$question',answer='$answer',category='$category',sort='$sort',status='$status' WHERE partnerfaqid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT partnerfaqid FROM faq WHERE faqid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO partnerfaq(partnerfaqid,created,question,answer,category,sort,status) VALUES ('$id','$created','$question','$answer','$category','$sort','$status')");
			}
		}

		public function Delete()
		{
			$db = $this->subscriber->GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM partnerfaq WHERE partnerfaqid='$id'");

			//Deleting Associated Objects
			/*n			$this->Category->Delete();
			*/
		}

		public static function Search(Subscriber $subscriber, $term='')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT partnerfaqid FROM partnerfaq WHERE question LIKE '%$term%' OR answer LIKE '%$term%'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Partnerfaq($subscriber);
                $ret[$i]->Initialize($row['partnerfaqid']);
				$i++;
			}
			return $ret;
		}

		public static function Filter(Subscriber $subscriber, $term='', $field='partnerfaqid', $sort_statement='')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT partnerfaqid FROM partnerfaq WHERE ".$field." ='$term' ".$sort_statement);
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Partnerfaq($subscriber);
                $ret[$i]->Initialize($row['partnerfaqid']);
				$i++;
			}
			return $ret;
		}

		public static function Order(Subscriber $subscriber, $field='id', $order='DESC')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT partnerfaqid FROM partnerfaq ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Partnerfaq($subscriber);
				$ret[$i]->Initialize($row['partnerfaqid']);
				$i++;
			}
			return $ret;
		}

		public static function All(Subscriber $subscriber)
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM partnerfaq");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Partnerfaq($subscriber);
				$ret[$i]->Id = $row['partnerfaqid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Question = $row['question'];
				$ret[$i]->Answer = $row['answer'];
				$ret[$i]->Category = new Partnerfaqcategory($row['category']);
				$ret[$i]->Sort = $row['sort'];
				$ret[$i]->Status = Convert::ToBool($row['status']);
				$i++;
			}
			return $ret;
		}
	}
