<?php
	/* Generated by Wixnit Class Builder 
	// Sep, 01/2019
	// Building class for Faqcategory
	*/

	class Partnerfaqcategory
	{
		public $Id = "";
		public $Created = 0;
		public $Name = "";
		public $Sort = 0;
		public $Status = false;
		
		private $subscriber = null;

		function __construct(Subscriber $subscriber)
		{
			$this->subscriber = $subscriber;
		}
		
		public function Initialize($arg=null)
		{
			if($arg != null)
			{
				$db = $this->subscriber->GetDB();

				$res = $db->query("SELECT * FROM partnerfaqcategory WHERE partnerfaqcategoryid='$arg'");

				if($res->num_rows > 0)
				{
					$row = $res->fetch_assoc();
				
					$this->Id = $row['partnerfaqcategoryid'];
					$this->Created = new WixDate($row['created']);
					$this->Name = $row['name'];
					$this->Sort = $row['sort'];
					$this->Status = Convert::ToBool($row['status']);
				}
			}
		}

		public function Save()
		{
			$db = $this->subscriber->GetDB();

			$id = $this->Id;
			$created = time();
			$name = addslashes($this->Name);
			$sort = Convert::ToInt($this->Sort);
			$status = Convert::ToInt($this->Status);

			if($res = $db->query("SELECT partnerfaqcategoryid FROM partnerfaqcategory WHERE partnerfaqcategoryid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE partnerfaqcategory SET name='$name',sort='$sort',status='$status' WHERE partnerfaqcategoryid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT partnerfaqcategoryid FROM partnerfaqcategory WHERE partnerfaqcategoryid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO partnerfaqcategory(partnerfaqcategoryid,created,name,sort,status) VALUES ('$id','$created','$name','$sort','$status')");
			}
		}

		public function Delete()
		{
			$db = $this->subscriber->GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM partnerfaqcategory WHERE partnerfaqcategoryid='$id'");
		}

		public static function Search(Subscriber $subscriber, $term='')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT partnerfaqcategoryid FROM partnerfaqcategory WHERE name LIKE '%$term%'");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Partnerfaqcategory($subscriber);
				$ret[$i]->Initialize($row['partnerfaqcategoryid']);
				$i++;
			}
			return $ret;
		}

		public static function Filter(Subscriber $subscriber, $term='', $field='partnerfaqcategoryid')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT partnerfaqcategoryid FROM partnerfaqcategory WHERE ".$field." ='$term'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Partnerfaqcategory($subscriber);
                $ret[$i]->Initialize($row['partnerfaqcategoryid']);
				$i++;
			}
			return $ret;
		}

		public static function Order(Subscriber $subscriber, $field='id', $order='DESC')
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT partnerfaqcategoryid FROM partnerfaqcategory ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Partnerfaqcategory($subscriber);
				$ret[$i]->Initialize($row['partnerfaqcategoryid']);
				$i++;
			}
			return $ret;
		}

		public static function All(Subscriber $subscriber)
		{
			$db = $subscriber->GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM partnerfaqcategory");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Partnerfaqcategory($subscriber);
				$ret[$i]->Id = $row['partnerfaqcategoryid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Name = $row['name'];
				$ret[$i]->Sort = $row['sort'];
				$ret[$i]->Status = Convert::ToBool($row['status']);
				$i++;
			}
			return $ret;
		}
	}
