<?php
	/* Generated by Wixnit Class Builder 
	// Apr, 19/2020
	// Building class for Policies
	*/

	class Policies
	{
		public $Id = "";
		public $Created = 0;
		public $Policiy = "";
		public $Description = "";
		public $Status = false;

		function __construct($arg=null)
		{
			if($arg != null)
			{
				$db = DB::GetDB();

				$res = $db->query("SELECT * FROM policies WHERE policiesid='$arg'");

				if($res->num_rows > 0)
				{
					$row = $res->fetch_assoc();
				
					$this->Id = $row['policiesid'];
					$this->Created = new WixDate($row['created']);
					$this->Policiy = $row['policiy'];
					$this->Description = $row['description'];
					$this->Status = Convert::ToBool($row['status']);
				}
			}
		}

		public function Save()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$created = time();
			$policiy = addslashes($this->Policiy);
			$description = addslashes($this->Description);
			$status = Convert::ToInt($this->Status);

			if($res = $db->query("SELECT policiesid FROM policies WHERE policiesid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE policies SET policiy='$policiy',description='$description',status='$status' WHERE policiesid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT policiesid FROM policies WHERE policiesid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO policies(policiesid,created,policiy,description,status) VALUES ('$id','$created','$policiy','$description','$status')");
			}
		}

		public function Delete()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM policies WHERE policiesid='$id'");
		}

		public static function Search($term='')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT policiesid FROM policies WHERE policiy LIKE '%$term%' OR description LIKE '%$term%' OR status LIKE '%$term%'");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Policies($row['policiesid']);
				$i++;
			}
			return $ret;
		}

		public static function Filter($term='', $field='policiesid')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT policiesid FROM policies WHERE ".$field." ='$term'");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Policies($row['policiesid']);
				$i++;
			}
			return $ret;
		}

		public static function Order($field='id', $order='DESC')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT policiesid FROM policies ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Policies($row['policiesid']);
				$i++;
			}
			return $ret;
		}

		public static function All()
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM policies");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Policies();
				$ret[$i]->Id = $row['policiesid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Policiy = $row['policiy'];
				$ret[$i]->Description = $row['description'];
				$ret[$i]->Status = Convert::ToBool($row['status']);
				$i++;
			}
			return $ret;
		}
	}
