<?php
	/* Generated by Wixnit Class Builder 
	// Jun, 27/2020
	// Building class for Reviews
	*/

	class Reviews
	{
		public $Id = "";
		public $Created = 0;
		public $Customer = "";
		public $Star = 0;
		public $Body = "";
		public $Property = "";

		function __construct($arg=null)
		{
			if($arg != null)
			{
				$db = DB::GetDB();

				$res = $db->query("SELECT * FROM reviews WHERE reviewsid='$arg'");

				if($res->num_rows > 0)
				{
					$row = $res->fetch_assoc();
				
					$this->Id = $row['reviewsid'];
					$this->Created = new WixDate($row['created']);
					$this->Customer = new Customer($row['customer']);
					$this->Star = $row['star'];
					$this->Body = $row['body'];
					$this->Property = new Property($row['property']);
				}
			}
		}

		public function Save()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$created = time();
			$customer = addslashes(is_a($this->Customer, "Customer") ? $this->Customer->Id : $this->Customer);
			$star = Convert::ToInt($this->Star);
			$body = addslashes($this->Body);
			$property = addslashes(is_a($this->Property, "Property") ? $this->Property->Id : $this->Property);

			if($res = $db->query("SELECT reviewsid FROM reviews WHERE reviewsid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE reviews SET customer='$customer',star='$star',body='$body',property='$property' WHERE reviewsid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT reviewsid FROM reviews WHERE reviewsid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO reviews(reviewsid,created,customer,star,body,property) VALUES ('$id','$created','$customer','$star','$body','$property')");
			}
		}

		public function Delete()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM reviews WHERE reviewsid='$id'");

			//Deleting Associated Objects
			/*n			$this->Customer->Delete();

			$this->Property->Delete();
			*/
		}

		public static function Search($term='')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT reviewsid FROM reviews WHERE customer LIKE '%$term%' OR star LIKE '%$term%' OR body LIKE '%$term%' OR property LIKE '%$term%'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Reviews();
                $ret[$i]->Id = $row['reviewsid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Customer = new Customer($row['customer']);
                $ret[$i]->Star = $row['star'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Property = $row['property'];
				$i++;
			}
			return $ret;
		}

		public static function Filter($term='', $field='reviewsid')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT reviewsid FROM reviews WHERE ".$field." ='$term'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Reviews();
                $ret[$i]->Id = $row['reviewsid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Customer = new Customer($row['customer']);
                $ret[$i]->Star = $row['star'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Property = $row['property'];
				$i++;
			}
			return $ret;
		}

		public static function Order($field='id', $order='DESC')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT reviewsid FROM reviews ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Reviews();
                $ret[$i]->Id = $row['reviewsid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Customer = new Customer($row['customer']);
                $ret[$i]->Star = $row['star'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Property = $row['property'];
				$i++;
			}
			return $ret;
		}

		public static function All()
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM reviews");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Reviews();
				$ret[$i]->Id = $row['reviewsid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Customer = new Customer($row['customer']);
				$ret[$i]->Star = $row['star'];
				$ret[$i]->Body = $row['body'];
				$ret[$i]->Property = $row['property'];
				$i++;
			}
			return $ret;
		}

        public static function ByProperty($property)
        {
            $db = DB::GetDB();
            $ret = array();
            $i = 0;

            $id = is_a($property, "Property") ? $property->Id : $property;

            $res = $db->query("SELECT * FROM reviews WHERE property='$id' ORDER BY id DESC LIMIT 0,5 ");
            while(($row = $res->fetch_assoc()) != null)
            {
                $ret[$i] = new Reviews();
                $ret[$i]->Id = $row['reviewsid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Customer = new Customer($row['customer']);
                $ret[$i]->Star = $row['star'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Property = $row['property'];
                $i++;
            }
            return $ret;
        }
	}
