<?php
	/* Generated by Wixnit Class Builder 
	// Mar, 27/2020
	// Building class for Session
	*/

	class Session
	{
		public $Id = "";
		public $Created = 0;
		public $Token = "";
		public $User = "";
		public $Span = 0;
		public $Currentitem = "";
		public $Itemname = "";

		function __construct($arg=null)
		{
			if($arg != null)
			{
				$db = DB::GetDB();

				$res = $db->query("SELECT * FROM session WHERE sessionid='$arg'");

				if($res->num_rows > 0)
				{
					$row = $res->fetch_assoc();
				
					$this->Id = $row['sessionid'];
					$this->Created = new WixDate($row['created']);
					$this->Token = $row['token'];
					$this->User = $row['user'];
					$this->Span = $row['span'];
					$this->Currentitem = $row['currentitem'];
					$this->Itemname = $row['itemname'];
				}
			}
		}

		public function Save()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$created = time();
			$token = addslashes($this->Token);
			$user = addslashes($this->User);
			$span = Convert::ToInt($this->Span);
			$currentitem = addslashes($this->Currentitem);
			$itemname = addslashes($this->Itemname);

			if($res = $db->query("SELECT sessionid FROM session WHERE sessionid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE session SET token='$token',user='$user',span='$span',currentitem='$currentitem',itemname='$itemname' WHERE sessionid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT sessionid FROM session WHERE sessionid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO session(sessionid,created,token,user,span,currentitem,itemname) VALUES ('$id','$created','$token','$user','$span','$currentitem','$itemname')");
			}
		}

		public function Delete()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM session WHERE sessionid='$id'");

			//Deleting Associated Objects
			/*n			$this->Span->Delete();
			*/
		}

		public static function Search($term='')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT sessionid FROM session WHERE token LIKE '%$term%' OR user LIKE '%$term%' OR span LIKE '%$term%'");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Session($row['sessionid']);
				$i++;
			}
			return $ret;
		}

		public static function Filter($term='', $field='sessionid')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT sessionid FROM session WHERE ".$field." ='$term'");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Session($row['sessionid']);
				$i++;
			}
			return $ret;
		}

		public static function Order($field='id', $order='DESC')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT sessionid FROM session ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Session($row['sessionid']);
				$i++;
			}
			return $ret;
		}

		public static function All()
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM session");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Session();
				$ret[$i]->Id = $row['sessionid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Token = $row['token'];
				$ret[$i]->User = $row['user'];
				$ret[$i]->Span = $row['span'];
                $ret[$i]->Currentitem = $row['currentitem'];
                $ret[$i]->Itemname = $row['itemname'];
				$i++;
			}
			return $ret;
		}


		public static function Start($token, $user)
        {
            $sess = new Session();
            $sess->User = $user;
            $sess->Token = $token;
            $sess->Span = time();
            $sess->Save();
        }

        public static function Stop($token)
        {
            $sess = Session::Get($token);
            if($sess != null)
            {
                $sess->Delete();
            }
        }

        public static function Get($token)
        {
            $db = DB::GetDB();
            $ret =  new Session();

            $res = $db->query("SELECT * FROM session WHERE token='$token'");
            if($res->num_rows > 0)
            {
                $row = $res->fetch_assoc();

                $ret = new Session();
                $ret->Id = $row['sessionid'];
                $ret->Created = new WixDate($row['created']);
                $ret->Token = $row['token'];
                $ret->User = $row['user'];
                $ret->Span = $row['span'];
                $ret->Currentitem = $row['currentitem'];
                $ret->Itemname = $row['itemname'];
            }
            return $ret;
        }

        public static function Exist($token)
        {
            $db = DB::GetDB();
            $ret = false;
            $res = $db->query("SELECT * FROM session WHERE token='$token'");

            if($res->num_rows > 0)
            {
                $ret = true;
            }
            return $ret;
        }

        public static function Refresh($token)
        {
            $sess = Session::Get($token);
            $sess->Span = time();
            $sess->Save();
        }

        public static function Find()
        {
            $ret = "";
            if(isset($_POST['token']))
            {
                if(Session::Exist($_POST['token']))
                {
                    $sess = Session::Get($_POST['token']);
                    $ret = $sess->User;
                }
            }
            else
            {
                if(isset($_SESSION))
                {
                    $keys = array_keys($_SESSION);

                    for($i = 0; $i < count($keys); $i++)
                    {
                        if(Session::Exist($keys[$i]))
                        {
                            $ret = $_SESSION[$keys[$i]];
                        }
                    }
                }
            }
            return $ret;
        }
	}
