<?php
	/* Generated by Wixnit Class Builder 
	// Jul, 01/2019
	// Building class for Ticketreply
	*/

	class Ticketreply
	{
		public $Id = "";
		public $Created = 0;
		public $Tcket_num = "";
		public $Body = "";
		public $Files = "";
		public $Source = "";

		function __construct($arg=null)
		{
			if($arg != null)
			{
				$db = DB::GetDB();

				$res = $db->query("SELECT * FROM ticketreply WHERE ticketreplyid='$arg'");

				if($res->num_rows > 0)
				{
					$row = $res->fetch_assoc();
				
					$this->Id = $row['ticketreplyid'];
					$this->Created = new WixDate($row['created']);
					$this->Tcket_num = $row['tcket_num'];
					$this->Body = $row['body'];
					$this->Files = $row['files'];
					$this->Source = $row['source'];
				}
			}
		}

		public function Save()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$created = time();
			$tcket_num = addslashes($this->Tcket_num);
			$body = addslashes($this->Body);
			$files = addslashes($this->Files);
			$source = addslashes($this->Source);

			if($res = $db->query("SELECT ticketreplyid FROM ticketreply WHERE ticketreplyid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE ticketreply SET tcket_num='$tcket_num',body='$body',files='$files',source='$source' WHERE ticketreplyid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT ticketreplyid FROM ticketreply WHERE ticketreplyid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO ticketreply(ticketreplyid,created,tcket_num,body,files,source) VALUES ('$id','$created','$tcket_num','$body','$files','$source')");
			}
		}

		public function Delete()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM ticketreply WHERE ticketreplyid='$id'");
		}

		public static function Search($term='')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT ticketreplyid FROM ticketreply WHERE tcket_num LIKE '%$term%' OR body LIKE '%$term%' OR files LIKE '%$term%'");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = $row['ticketreplyid'];
				$i++;
			}
			return Ticketreply::GroupInitialize($ret);
		}

		public static function Filter($term='', $field='ticketreplyid')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT ticketreplyid FROM ticketreply WHERE ".$field." ='$term'");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = $row['ticketreplyid'];
				$i++;
			}
			return Ticketreply::GroupInitialize($ret);
		}

		public static function Order($field='id', $order='DESC')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT ticketreplyid FROM ticketreply ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = $row['ticketreplyid'];
				$i++;
			}
			return Ticketreply::GroupInitialize($ret);
		}

		public static function GroupInitialize($array=null, $orderBy='id', $order='DESC')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$query = "";

			if(is_array($array) === true)
			{
				if(count($array) == 0)
				{
					return $ret;
				}
				else
				{
					for($i = 0; $i < count($array); $i++)
					{
						if($query == "")
						{
							$query = " WHERE Ticketreplyid='".$array[$i]."'";
						}
						else
						{
							$query .= " OR Ticketreplyid ='".$array[$i]."'";
						}
					}
				}
			}
			$i = 0;
			$res = $db->query("SELECT * FROM ticketreply".$query." ORDER BY ".$orderBy." ".$order);
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Ticketreply();
				$ret[$i]->Id = $row['ticketreplyid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Tcket_num = $row['tcket_num'];
				$ret[$i]->Body = $row['body'];
				$ret[$i]->Files = $row['files'];
				$ret[$i]->Source = $row['source'];
				$i++;
			}
			return $ret;
		}

		public static function GetReplies($ticket)
        {
            $ret = array();
            $i = 0;
            $tck = is_a($ticket, "Ticket") ? $ticket->Id : $ticket;

            $res = DB::GetDB()->query("SELECT * FROM ticketreply WHERE tcket_num='$tck'");

            while(($row = $res->fetch_assoc()) != null)
            {
                $ret[$i] = new Ticketreply();
                $ret[$i]->Id = $row['ticketreplyid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Tcket_num = $row['tcket_num'];
                $ret[$i]->Body = $row['body'];
                $ret[$i]->Files = $row['files'];
                $ret[$i]->Source = $row['source'];
                $i++;
            }
            return $ret;
        }
	}
