<?php
	/* Generated by Wixnit Class Builder 
	// May, 14/2020
	// Building class for Withdrawal
	*/

	class Withdrawal
	{
		public $Id = "";
		public $Created = 0;
		public $Item = "";
		public $Itemtype = "";
		public $Month = 0;
		public $Year = 0;
		public $Amount = 0;
		public $Paid = false;
		public $Declined = false;
		public $Owner = "";

		function __construct($arg=null)
		{
			if($arg != null)
			{
				$db = DB::GetDB();

				$res = $db->query("SELECT * FROM withdrawal WHERE withdrawalid='$arg'");

				if($res->num_rows > 0)
				{
					$row = $res->fetch_assoc();
				
					$this->Id = $row['withdrawalid'];
					$this->Created = new WixDate($row['created']);
					$this->Item = $row['item'];
					$this->Itemtype = $row['itemtype'];
					$this->Month = $row['month'];
					$this->Year = $row['year'];
					$this->Amount = $row['amount'];
					$this->Paid = Convert::ToBool($row['paid']);
					$this->Declined = Convert::ToBool($row['declined']);
					$this->Owner = new Customer($GLOBALS['subcriber']);
					$this->Owner->Initialize($row['owner']);
				}
			}
		}

		public function Save()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$created = time();
			$item = addslashes($this->Item);
			$itemtype = addslashes($this->Itemtype);
			$month = Convert::ToInt($this->Month);
			$year = Convert::ToInt($this->Year);
			$amount = floatval($this->Amount);
			$paid = Convert::ToInt($this->Paid);
			$declined = Convert::ToInt($this->Declined);
			$owner = is_a($this->Owner, "Customer") ? $this->Owner->Id : $this->Owner;

			if($res = $db->query("SELECT withdrawalid FROM withdrawal WHERE withdrawalid='$id'")->num_rows > 0)
			{
				$db->query("UPDATE withdrawal SET item='$item',itemtype='$itemtype',month='$month',year='$year',amount='$amount',paid='$paid',declined='$declined',owner='$owner' WHERE withdrawalid = '$id'");
			}
			else
			{
				redo: ;
				$id = Random::GenerateId(16);
				if($db->query("SELECT withdrawalid FROM withdrawal WHERE withdrawalid='$id'")->num_rows > 0)
				{
					goto redo;
				}
				$this->Id = $id;
				$db->query("INSERT INTO withdrawal(withdrawalid,created,item,itemtype,month,year,amount,paid,declined,owner) VALUES ('$id','$created','$item','$itemtype','$month','$year','$amount','$paid','$declined','$owner')");
			}
		}

		public function Delete()
		{
			$db = DB::GetDB();

			$id = $this->Id;
			$db->query("DELETE FROM withdrawal WHERE withdrawalid='$id'");
		}

		public static function Search($term='')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM withdrawal WHERE item LIKE '%$term%' OR itemtype LIKE '%$term%' OR month LIKE '%$term%' OR year LIKE '%$term%' OR amount LIKE '%$term%' OR paid LIKE '%$term%' OR declined LIKE '%$term%'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Withdrawal();
                $ret[$i]->Id = $row['withdrawalid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Item = $row['item'];
                $ret[$i]->Itemtype = $row['itemtype'];
                $ret[$i]->Month = $row['month'];
                $ret[$i]->Year = $row['year'];
                $ret[$i]->Amount = $row['amount'];
                $ret[$i]->Paid = Convert::ToBool($row['paid']);
                $ret[$i]->Declined = Convert::ToBool($row['declined']);
                $ret[$i]->Owner = $row['owner'];
				$i++;
			}
			return $ret;
		}

		public static function Filter($term='', $field='withdrawalid')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM withdrawal WHERE ".$field." ='$term'");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Withdrawal();
                $ret[$i]->Id = $row['withdrawalid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Item = $row['item'];
                $ret[$i]->Itemtype = $row['itemtype'];
                $ret[$i]->Month = $row['month'];
                $ret[$i]->Year = $row['year'];
                $ret[$i]->Amount = $row['amount'];
                $ret[$i]->Paid = Convert::ToBool($row['paid']);
                $ret[$i]->Declined = Convert::ToBool($row['declined']);
                $ret[$i]->Owner = $row['owner'];
				$i++;
			}
			return $ret;
		}

		public static function Order($field='id', $order='DESC')
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM withdrawal ORDER BY ".$field." ".$order."");
			while(($row = $res->fetch_assoc()) != null)
			{
                $ret[$i] = new Withdrawal();
                $ret[$i]->Id = $row['withdrawalid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Item = $row['item'];
                $ret[$i]->Itemtype = $row['itemtype'];
                $ret[$i]->Month = $row['month'];
                $ret[$i]->Year = $row['year'];
                $ret[$i]->Amount = $row['amount'];
                $ret[$i]->Paid = Convert::ToBool($row['paid']);
                $ret[$i]->Declined = Convert::ToBool($row['declined']);
                $ret[$i]->Owner = $row['owner'];
				$i++;
			}
			return $ret;
		}

		public static function All()
		{
			$db = DB::GetDB();
			$ret = array();
			$i = 0;

			$res = $db->query("SELECT * FROM withdrawal");
			while(($row = $res->fetch_assoc()) != null)
			{
				$ret[$i] = new Withdrawal();
				$ret[$i]->Id = $row['withdrawalid'];
				$ret[$i]->Created = new WixDate($row['created']);
				$ret[$i]->Item = $row['item'];
				$ret[$i]->Itemtype = $row['itemtype'];
				$ret[$i]->Month = $row['month'];
				$ret[$i]->Year = $row['year'];
				$ret[$i]->Amount = $row['amount'];
				$ret[$i]->Paid = Convert::ToBool($row['paid']);
				$ret[$i]->Declined = Convert::ToBool($row['declined']);
				$ret[$i]->Owner = $row['owner'];
				$i++;
			}
			return $ret;
		}

        public static function ByUser($customer)
        {
            $db = DB::GetDB();
            $ret = array();
            $i = 0;

            $id = is_a($customer, "Customer") ? $customer->Id : $customer;

            $res = $db->query("SELECT * FROM withdrawal where owner='$id'");
            while(($row = $res->fetch_assoc()) != null)
            {
                $ret[$i] = new Withdrawal();
                $ret[$i]->Id = $row['withdrawalid'];
                $ret[$i]->Created = new WixDate($row['created']);
                $ret[$i]->Item = $row['item'];
                $ret[$i]->Itemtype = $row['itemtype'];
                $ret[$i]->Month = $row['month'];
                $ret[$i]->Year = $row['year'];
                $ret[$i]->Amount = $row['amount'];
                $ret[$i]->Paid = Convert::ToBool($row['paid']);
                $ret[$i]->Declined = Convert::ToBool($row['declined']);
                $ret[$i]->Owner = $row['owner'];
                $i++;
            }
            return $ret;
        }
	}
